name: python-app-60-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: jaimehenao8126/python-app-60:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v3

      - name: Modify values file
        shell: bash
        run: |
          echo ${{needs.ci.outputs.commit_id}}
          pip install yq
          values_file="charts/python-app-60/values-dev1.yaml"
          if [ ! -f "$values_file" ]; then
            echo "ERROR: $values_file does not exist."
            exit 1
          fi
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' "$values_file"

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{needs.ci.outputs.commit_id}}'

      - name: Install argocd
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ secrets.ARGOCD_PASSWORD }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |

          # Connects the argocd repo
          repo="https://github.com/Portfolio-jaime/python-app-60.git"
          argocd repo list | grep -q $repo || argocd repo add $repo --project default

          # Creates the argocd app
          argocd app get python-app-60 || argocd app create python-app-60 \
            --repo $repo \
            --path charts/python-app-60 \
            --dest-namespace dev1 \
            --dest-server https://kubernetes.default.svc \
            --values values-dev1.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true \
            --project default

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync python-app-60
          argocd app wait python-app-60 --timeout 180